//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasselApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WasselApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Application.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DropOff.
        /// </summary>
        internal static string AddDropOff {
            get {
                return ResourceManager.GetString("AddDropOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please , Add All Required Images First .
        /// </summary>
        internal static string AddImages {
            get {
                return ResourceManager.GetString("AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Liecence Image.
        /// </summary>
        internal static string AddLiecnceImg {
            get {
                return ResourceManager.GetString("AddLiecnceImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert !.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please , Choose Car Model.
        /// </summary>
        internal static string AllModels {
            get {
                return ResourceManager.GetString("AllModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please , Choose The Type.
        /// </summary>
        internal static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Log Out ?.
        /// </summary>
        internal static string AskLogOUt {
            get {
                return ResourceManager.GetString("AskLogOUt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        internal static string Callus {
            get {
                return ResourceManager.GetString("Callus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Number.
        /// </summary>
        internal static string Carid {
            get {
                return ResourceManager.GetString("Carid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Model.
        /// </summary>
        internal static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type.
        /// </summary>
        internal static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Check Your Email &amp; PassWord.
        /// </summary>
        internal static string ChecEP {
            get {
                return ResourceManager.GetString("ChecEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please , Choose Car Type.
        /// </summary>
        internal static string ChooseCarType {
            get {
                return ResourceManager.GetString("ChooseCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Place From Pin On Map.
        /// </summary>
        internal static string ChoosePlace {
            get {
                return ResourceManager.GetString("ChoosePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Choose Your Residence.
        /// </summary>
        internal static string ChooseResidence {
            get {
                return ResourceManager.GetString("ChooseResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Booking.
        /// </summary>
        internal static string ConfirmBooking {
            get {
                return ResourceManager.GetString("ConfirmBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Pass Word.
        /// </summary>
        internal static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Your Connection.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination From.
        /// </summary>
        internal static string DestinationFrom {
            get {
                return ResourceManager.GetString("DestinationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Destinationto {
            get {
                return ResourceManager.GetString("Destinationto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter As Driver.
        /// </summary>
        internal static string DriverUse {
            get {
                return ResourceManager.GetString("DriverUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email has already been taken..
        /// </summary>
        internal static string EmailTaken {
            get {
                return ResourceManager.GetString("EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please , Check Your Network Connection.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Is Required .
        /// </summary>
        internal static string FieldReq {
            get {
                return ResourceManager.GetString("FieldReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frieght Cars.
        /// </summary>
        internal static string FrieghtCars {
            get {
                return ResourceManager.GetString("FrieghtCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have Account , Already ?.
        /// </summary>
        internal static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number.
        /// </summary>
        internal static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address Format.
        /// </summary>
        internal static string InvalidMail {
            get {
                return ResourceManager.GetString("InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Liecence Image.
        /// </summary>
        internal static string LiecenceImages {
            get {
                return ResourceManager.GetString("LiecenceImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load of the Car in kg.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Location is Required.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, This Location doesn&apos;t have Address .
        /// </summary>
        internal static string LocationNotFound {
            get {
                return ResourceManager.GetString("LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Place.
        /// </summary>
        internal static string LocationTo {
            get {
                return ResourceManager.GetString("LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOUt {
            get {
                return ResourceManager.GetString("LogOUt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Way.
        /// </summary>
        internal static string MyWay {
            get {
                return ResourceManager.GetString("MyWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PassWord.
        /// </summary>
        internal static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No !.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Place From As There is no Order.
        /// </summary>
        internal static string NoPlaceFrom {
            get {
                return ResourceManager.GetString("NoPlaceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Place To As there is no Order.
        /// </summary>
        internal static string NoPlaceTo {
            get {
                return ResourceManager.GetString("NoPlaceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notes.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current PassWord.
        /// </summary>
        internal static string OldPass {
            get {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Now.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , Your Order was Refused.
        /// </summary>
        internal static string OrderRefused {
            get {
                return ResourceManager.GetString("OrderRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Goals.
        /// </summary>
        internal static string OurGoals {
            get {
                return ResourceManager.GetString("OurGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PassPort Image.
        /// </summary>
        internal static string PassPortNum {
            get {
                return ResourceManager.GetString("PassPortNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Word.
        /// </summary>
        internal static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassWord Doesn&apos;t Match.
        /// </summary>
        internal static string PassWordMatch {
            get {
                return ResourceManager.GetString("PassWordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassWord consists of 6 lenght , contains at least one digit &amp; alphabet.
        /// </summary>
        internal static string PassWordValid {
            get {
                return ResourceManager.GetString("PassWordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to take photos..
        /// </summary>
        internal static string PermissionDetails {
            get {
                return ResourceManager.GetString("PermissionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Can&apos;t Get Your Location.
        /// </summary>
        internal static string PermissionLocationDetails {
            get {
                return ResourceManager.GetString("PermissionLocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Denied.
        /// </summary>
        internal static string PermissionsDenied {
            get {
                return ResourceManager.GetString("PermissionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUp Location.
        /// </summary>
        internal static string PickUpLocation {
            get {
                return ResourceManager.GetString("PickUpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile Image.
        /// </summary>
        internal static string ProfileImages {
            get {
                return ResourceManager.GetString("ProfileImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence.
        /// </summary>
        internal static string Residence {
            get {
                return ResourceManager.GetString("Residence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resident.
        /// </summary>
        internal static string resident {
            get {
                return ResourceManager.GetString("resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Citizen.
        /// </summary>
        internal static string Saudi {
            get {
                return ResourceManager.GetString("Saudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Car Type.
        /// </summary>
        internal static string SelectCarType {
            get {
                return ResourceManager.GetString("SelectCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing PassWord.
        /// </summary>
        internal static string SettingsPass {
            get {
                return ResourceManager.GetString("SettingsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have Registered Successfully !.
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter As User.
        /// </summary>
        internal static string UserUse {
            get {
                return ResourceManager.GetString("UserUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick Cars.
        /// </summary>
        internal static string Waselbrick {
            get {
                return ResourceManager.GetString("Waselbrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Cars.
        /// </summary>
        internal static string WaselShahn {
            get {
                return ResourceManager.GetString("WaselShahn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes !.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
